services:
  finger-detection-service:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./model:/app/model
    environment:
      - PYTHONPATH=/app
      - BLAS=/usr/lib/libopenblas.so
      - OPENBLAS_NUM_THREADS=1
      - OPENCV_IO_MAX_IMAGE_PIXELS=2147483647
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching if needed later
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
