global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hand Gesture Recognition Service
  - job_name: 'hand-gesture-service'
    static_configs:
      - targets: ['hand-gesture-service:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  # Node Exporter is a Prometheus exporter for hardware and OS metrics exposed by *NIX kernels. 
  # It is used to collect system-level metrics such as CPU, memory, disk, and network statistics, 
  # which are useful for monitoring the health and performance of the underlying infrastructure 
  # where your services are running.

  # Node Exporter (if you want system metrics)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
